version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            -   ./:/var/www/Tutorial/Dimitriy
        ports:
            -   "8080:80"
        links:
            -   php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/pgp-fpm.docker
        volumes:
            -   ./:var/www/Tutorial/Dimitriy
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        links:
            -   mysql
            -   redis
    mysql:
        image: mysql:8.0
        volumes:
            - ./storage/docker/myqsl:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=Tissot_1853@"
            - "MYSQL_USER=root"
            - "MYSQL_PASSWORD=Tissot_1853@"
            - "MYSQL_DATABASE=dmitriy"

        ports:
            - "33061:3306"
    redis:
        image: redis:3.0
        ports:
            -   "63791:6379"



